from __future__ import annotations

JARVIS_SYSTEM_NAME = "JARVIS_OS"
RUNTIME_VERSION = "0.1.0"

DEFAULT_LOG_LEVEL = "INFO"

DEFAULT_EVENT_QUEUE_SIZE = 1000
DEFAULT_WORKER_TIMEOUT_SECONDS = 30
DEFAULT_HEALTH_CHECK_INTERVAL_SECONDS = 5
DEFAULT_RETRY_COUNT = 3
MAX_CONCURRENT_TASKS = 100

DEFAULT_RUNTIME_YAML = "runtime.yaml"
DEFAULT_PERMISSIONS_YAML = "permissions.yaml"